# Args: <obj_file1> <obj_file2> <output_dir>
{
  "version": 2,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "blender_version": "blender-2.81",
    "pip": [
      "h5py",
      "imageio"
    ]
  },
  "global": {
    "all": {
      "output_dir": "<args:2>"
    }
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {}
    },
    {
      "module": "loader.ObjectLoader",
      "config": {
        "path": "<args:0>",
        "add_properties": {
           "physics": True
        }
      }
    },
    {
      "module": "loader.ObjectLoader",
      "config": {
        "path": "<args:1>",
        "add_properties": {
          "physics": False
        }
      }
    },
    {
      "module": "object.ObjectPoseSampler",
      "config":{
        "objects_to_sample": {
          "provider": "getter.Entity",
          "conditions": {
            "physics": True,
            "type": "MESH"
          }
        },
        "pos_sampler":{
          "provider":"sampler.Uniform3d",
          "max":[5, 5, 8],
          "min":[-5, -5, 12]
        },
        "rot_sampler":{
          "provider":"sampler.UniformSO3"
        }
      }
    },
    {
      "module": "lighting.LightLoader",
      "config": {
        "lights": [
          {
            "type": "SUN",
            "location": [0, 0, 0],
            "rotation": [-0.063, 0.6177, -0.1985],
            "energy": 1,
            "color": [1, 0.978, 0.407]
          }
        ]
      }
    },
    {
      "module": "camera.CameraLoader",
      "config": {
        "cam_poses": [
          {
            "location": [0, -47.93, 16.59],
            "rotation": {
              "value": [1.3, 0, 0]
            }
          }
        ]
      }
    },
    {
      "module": "object.PhysicsPositioning",
      "config": {
        "min_simulation_time": 4,
        "max_simulation_time": 20,
        "check_object_interval": 1
      }
    },
    {
      "module": "renderer.RgbRenderer"
    },
    {
      "module": "writer.Hdf5Writer"
    }
  ]
}
