# Args: <cam_file> <obj_file> <output_dir>
{
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "blender_version": "blender-2.81-linux-glibc217-x86_64",
    "pip": [
      "h5py",
      "imageio"
    ]
  },
  "global": {
    "all": {
      "output_dir": "<args:0>"
    }
  },
  "modules": [
    {
      "name": "main.Initializer",
      "config": {}
    },
    {
      "name": "loader.ObjectLoader",
      "config": {
        "path": "examples/physics_positioning/active.obj",
        "physics": "active"
      }
    },
    {
      "name": "object.ObjectPoseSampler",
      "config":{
        "pos_sampler":{
          "name":"sampler.Uniform3d",
          "parameters":{
            "max":[5, 5, 8],
            "min":[-5, -5, 12]
          }
        },
        "rot_sampler":{
          "name":"sampler.Uniform3d",
          "parameters":{
            "max":[0, 0, 0],
            "min":[6.28, 6.28, 6.28]
          }
        }
      }
    },
    {
      "name": "loader.ObjectLoader",
      "config": {
        "path": "examples/physics_positioning/passive.obj"
      }
    },
    {
      "name": "lighting.LightLoader",
      "config": {
        "lights": [
          {
            "type": "SUN",
            "location": [0, 0, 0],
            "rotation": [-0.063, 0.6177, -0.1985],
            "energy": 1,
            "color": [1, 0.978, 0.407]
          }
        ]
      }
    },
    {
      "name": "camera.CameraLoader",
      "config": {
        "cam_poses": [
          {
            "location": [0, -47.93, 16.59],
            "rotation": {
              "value": [1.3, 0, 0]
            }
          }
        ]
      }
    },
    {
      "name": "object.PhysicsPositioning",
      "config": {
        "min_simulation_time": 4,
        "max_simulation_time": 20,
        "check_object_interval": 1
      }
    },
    {
      "name": "renderer.RgbRenderer"
    },
    {
      "name": "writer.Hdf5Writer"
    }
  ]
}