# Args: <cam_file> <obj_file> <output_dir>
{
  "version": 2,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "blender_version": "blender-2.81-linux-glibc217-x86_64",
    "pip": [
      "h5py",
      "imageio"
    ]
  },
  "global": {
    "all": {
      "output_dir": "<args:2>"
    }
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {}
    },
    {
      "module": "loader.ObjectLoader",
      "config": {
        "path": "<args:1>"
      }
    },
    {
      "module": "lighting.LightLoader",
      "config": {
        "lights": [
          {
            "type": "POINT",
            "location": [5, -5, 5],
            "energy": 1000
          }
        ]
      }
    },
    {
      "module": "camera.CameraLoader",
      "config": {
        "path": "<args:0>",
        "file_format": "location rotation/value",
        "default_cam_param": {
          "fov": 1
        }
      }
    },
    {
      "module": "object.ObjectPoseSampler",
      "config":{
        "max_iterations": 1000,
        "pos_sampler": {
          "provider": "sampler.Uniform3d",
          "max": [5,5,5],
          "min": [-5,-5,-5]
        },
        "rot_sampler":{
          "provider": "sampler.Uniform3d",
          "max": [0,0,0],
          "min": [6.28,6.28,6.28]
        }
      }
    },
    {
      "module": "renderer.NormalRenderer",
      "config": {
        "output_key": "normals"
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "output_key": "colors",
        "samples": 50
      }
    },
    {
      "module": "writer.Hdf5Writer",
      "config": {
      }
    }
  ]
}