# Args: <cam_file> <obj_file> <output_dir>
{
  "version": 2,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py"
    ]
  },
  "global": {
    "all": {
      "output_dir": "<args:2>"
    }
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {}
    },
    {
      "module": "loader.ObjectLoader",
      "config": {
        "path": "<args:1>",
        "add_properties": {
          "sample_pose": True
        }
      }
    },
    {
      "module": "lighting.LightLoader",
      "config": {
        "lights": [
          {
            "type": "POINT",
            "location": [5, -5, 5],
            "energy": 1000
          }
        ]
      }
    },
    {
      "module": "camera.CameraLoader",
      "config": {
        "path": "<args:0>",
        "file_format": "location rotation/value",
        "default_cam_param": {
          "fov": 1
        }
      }
    },
    {
      "module": "object.ObjectPoseSampler",
      "config":{
        "max_iterations": 1000,
        "objects_to_sample": {
          "provider": "getter.Entity",
          "conditions": {
            "sample_pose": True,
            "type": "MESH"
          }
        },
        "pos_sampler": {
          "provider": "sampler.Uniform3d",
          "max": [5,5,5],
          "min": [-5,-5,-5]
        },
        "rot_sampler": {
          "provider": "sampler.Uniform3d",
          "max": [0,0,0],
          "min": [6.28,6.28,6.28]
        }
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "output_key": "colors",
        "samples": 50,
        "render_normal": True,
        "output_is_temp": False
      }
    },
    {
      "module": "writer.Hdf5Writer",
    }
  ]
}
