# Args: <cam_file> <obj_file> <output_dir>
{
  "setup": {
    "blender_install_path": "/path/to/blender",
    "blender_version": "blender-2.80-linux-glibc217-x86_64",
    "bop_toolkit_path": "/path/to/bop_toolkit",
    "pip": [
      "h5py",
      "imageio",
      "pypng==0.0.20",
      "scipy==1.2.2"
    ]
  },
  "global": {
    "all": {
      "output_dir": "<args:1>"
    }
  },
  "modules": [
    {
      "name": "main.Initializer",
      "config": {}
    },
    {
      "name": "loader.BopLoader",
      "config": {
        "bop_dataset_path": "<args:0>",
        "mm2m": True,
        "split": "test",
        "scene_id": 3,
        "model_type": ""
      }
    },
    {
      "name": "lighting.LightSampler",
      "config": {
        "lights": [
          {
            "location": {
              "name": "ShellSampler",
              "parameters": {
                "center": [0, 0, -0.8],
                "radius_min": 1,
                "radius_max": 4,
                "elevation_min": 1,
                "elevation_max": 89
              }
            },
            "type": "POINT",
            "energy": 1000
          }
        ]
      }
    },
    # {
    #   "name": "lighting.LightLoader",
    #   "config": {
    #     "lights": [
    #       {
    #         "type": "AREA",
    #         "location": [0, 0, 0],
    #         "energy": 10000,
    #         "shape": "SQUARE",
    #         "size": 30
    #       }
    #     ]
    #   }
    # },
    #   {
    #   "name": "object.PositionSampler",
    #   "config":{
    #     "max_iterations": 1000,
    #     "pos_sampler":{
    #       "name":"Uniform3dSampler",
    #       "parameters":{
    #         "max":[0.1,0.1,0.8],
    #         "min":[-0.1,-0.1,1.2]
    #       }
    #     },
    #     "rot_sampler":{
    #       "name":"Uniform3dSampler",
    #       "parameters":{
    #         "max":[0,0,0],
    #         "min":[6.28,6.28,6.28]
    #       }
    #     }
    #   }
    # },
    # {
    #   "name": "renderer.NormalRenderer",
    #   "config": {
    #   }
    # },
    {
      "name": "renderer.RgbRenderer",
      "config": {
        "samples": 150
      }
    },
    {
      "name": "writer.Hdf5Writer",
      "config": {
      }
    }
  ]
}
