# Args: <path_to_re_dataset> <output_dir>
{
  "version": 2,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py",
      "scikit-image"
    ]
  },
  "global": {
    "all": {
      "output_dir": "<args:1>",
      "append_to_existing_output": True
    }
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {}
    },
    {
      "module": "loader.RockEssentialsRockLoader",
      "config": {
        "batches": [
        {
          "path": "<args:0>/Rock Essentials/Individual Rocks/Sea/Rocks_Sea_Large.blend",
          "objects": ['Rock_Sea_Large001','Rock_Sea_Large003'],
          "physics": False,
          "render_levels": 2,
          "high_detail_mode": True
        },
        {
          "path": "<args:0>/Rock Essentials/Individual Rocks/Granite/Rocks_Granite_Medium.blend",
          "amount": 10,
          "physics": True,
          "render_levels": 2,
          "high_detail_mode": False,
          "scale": [1.5, 1.5, 1.5]
        },
        {
          "path": "<args:0>/Rock Essentials/Individual Rocks/Desert/Rocks_Desert_Medium.blend",
          "amount": 15,
          "physics": True,
          "render_levels": 2,
          "high_detail_mode": False,
          "scale": [1.5, 1.5, 1.5]
        },
        {
          "path": "<args:0>/Rock Essentials/Individual Rocks/Forest/Rocks_Forest_Large.blend",
          "objects": ['Rock_Forest_Large002', 'Rock_Forest_Large012'],
          "physics": False,
          "render_levels": 2,
          "high_detail_mode": False
        }
        ]
      }
    },
    {
      "module": "constructor.RockEssentialsGroundConstructor",
      "config": {
        "tiles": [
        {
          "shader_path": "<args:0>/Rock Essentials/Individual Rocks/Volcanic/Rocks_Volcanic_Small.blend",
          "plane_scale": [50, 50, 1],
          "subdivision_cuts": 30,
          "subdivision_render_levels": 2,
          "displacement_strength": 0.7,
          "AO": [0.5, 0.5, 0.5, 1],
          "tile_name": "Gr_Plane_1"
        }
        ]
      }
    },
    {
      "module": "materials.RockEssentialsTextureSampler",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "name": "Gr_Plane.*",
            "type": "MESH"
          }
        },
        "textures": [
        {
          "path": "<args:0>/Rock Essentials/Ground Textures/Pebbles/RDTGravel001/",
          "uv_scaling": 9,
          "images": {
            "color": "RDTGravel001_COL_VAR1_3K.jpg",
            "roughness": "RDTGravel001_GLOSS_3K.jpg",
            "reflection": "RDTGravel001_REFL_3K.jpg",
            "normal": "RDTGravel001_NRM_3K.jpg",
            "displacement": "RDTGravel001_DISP16_3K.tif"
          }
        },
        ]
      }
    },
    {
      "module": "object.EntityManipulator",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "name": '.*Large.*'
          }
        },
        "location": {
          "provider": "sampler.Uniform3d",
          "max":[5, 5, -0.1],
          "min":[-5, -5, -0.1]
        }
      }
    },
    {
      "module": "object.ObjectPoseSampler",
      "config":{
        "objects_to_sample": {
          "provider": "getter.Entity",
          "conditions": {
            "physics": True,
            "type": "MESH"
          }
        },
        "pos_sampler":{
          "provider":"sampler.Uniform3d",
          "max":[5, 5, 4],
          "min":[-5, -5, 2]
        },
        "rot_sampler":{
          "provider":"sampler.Uniform3d",
          "max":[5, 5, 5],
          "min":[0, 0, 0]
        }
      }
    },
    {
      "module": "camera.CameraSampler",
      "config": {
        "cam_poses": [
        {
          "number_of_samples": 5,
          "location": {
            "provider": "sampler.Disk",
            "center": [0, 0, 4],
            "radius": 7,
            "use_circle_only": True
          },
          "rotation": {
            "format": "look_at",
            "value": {
              "provider":"sampler.Uniform3d",
              "max": [4, 4, 0],
              "min": [-4, -4, 0]
            }
          }
        }
        ]
      }
    },
    {
      "module": "lighting.LightLoader",
      "config": {
        "lights": [
        {
          "type": "SUN",
          "location": {
            "provider": "sampler.Shell",
            "center": [0, 0, 0],
            "radius_min": 6,
            "radius_max": 12,
            "elevation_min": 10,
            "elevation_max": 80
          },
          "rotation": [-0.063, 0.6177, -0.1985],
          "energy": {
            "provider": "sampler.Value",
            "type": "float",
            "min": 10,
            "max": 30
          },
          "color": [1, 1, 1]
        }
        ]
      }
    },
    {
      "module": "object.PhysicsPositioning",
      "config": {
        "min_simulation_time": 2,
        "max_simulation_time": 5,
        "check_object_interval": 1,
        "solver_iters": 25,
        "steps_per_sec": 200
      }
    },
    {
      "module": "object.EntityManipulator",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "name": "Gr_Plane_1"
          }
        },
        "location": [0, 0, 0.05]
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "output_key": "colors",
        "samples": 128,
        "resolution_x": 640,
        "resolution_y": 480
      }
    },
    {
      "module": "renderer.SegMapRenderer",
      "config": {
        "map_by": "instance",
        "resolution_x": 640,
        "resolution_y": 480
      }
    },
    {
      "module": "writer.CocoAnnotationsWriter",
      "config": {
      }
    }
  ]
}
