# Args: <path_to_shape-net-core> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config":{
        "global": {
          "output_dir": "<args:1>"
        }
      }
    },
    {
      "module": "loader.ShapeNetLoader",
      "config": {
        "data_path": "<args:0>",
        "used_synset_id": "03001627"
      }
    },
    {
      "module": "lighting.LightLoader",
      "config": {
        "lights": [
          {
            "type": "POINT",
            "location": [5, -5, 5],
            "energy": 1000
          }
        ]
      }
    },
    {
      "module": "camera.CameraSampler",
      "config": {
        "cam_poses": [
          {
            "number_of_samples": 5,
            "location": {
              "provider":"sampler.Sphere",
              "center":[0, 0, 0],
              "radius": 2,
              "mode": "SURFACE"
            },
            "rotation": {
              "format": "look_at",
              "value": {
                "provider": "getter.POI"
              }
            }
          }
        ]
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "transparent_background": False,
        "render_alpha": False,
        "render_normals": True,
        "samples": 350,
        "render_distance": true
      }
    },
    {
      "module": "writer.Hdf5Writer",
      "config": {
        "store_alpha": False,
        "postprocessing_modules": {
          "distance": [
            {
              "module": "postprocessing.TrimRedundantChannels",
              "config": {}
            }
          ]
        }
      }
    }
  ]
}
