# Args: <cam_file> <obj_file> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py",
      "numpy",
      "Pillow",
      "opencv-contrib-python",
      "scipy",
      "git+https://github.com/abahnasy/smplx",
      "git+https://github.com/abahnasy/human_body_prior",
      "scikit-image",
      "pypng==0.0.20",

      "m2r2==0.2.7",
      #"recommonmark==0.6.0",
      "sphinx-autodoc-typehints==1.6.0",
      "sphinx_rtd_theme==0.4.3",
      "Sphinx==1.8.5"
    ]
  },
  "modules": [
  ]
}
