# Args: <bop_dataset_path> <bop_toolkit_path> <output_dir>
{
  "version": 3,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "pip": [
      "h5py",
      "scikit-image",
      "pypng==0.0.20",
      "scipy==1.2.2"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {
        "global": {
          "output_dir": "<args:2>",
          "sys_paths": ["<args:1>"] # path to the bop toolkit
        }
      }
    },
    {
      "module": "loader.BopLoader",
      "config": {
        "bop_dataset_path": "<args:0>",
        "mm2m": True,
        "split": "test", # careful, some BOP datasets only have test sets
        "scene_id": 1,
        "model_type": ""
      }
    },
    {
      "module": "lighting.LightSampler",
      "config": {
        "lights": [
          {
            "location": {
              "provider": "sampler.Shell",
              "center": [0, 0, -0.8],
              "radius_min": 2,
              "radius_max": 4,
              "elevation_min": 40,
              "elevation_max": 89
            },
            "type": "POINT",
            "energy": 1000
          }
        ]
      }
    },
    {
      "module": "renderer.RgbRenderer",
      "config": {
        "samples": 150
      }
    },
    {
      "module": "renderer.SegMapRenderer",
      "config": {
        "map_by": "instance"
      }
    },
    {
      "module": "writer.BopWriter",
      "dataset": "hb",
      "postprocessing_modules": {
        "depth": [
          {"module": "postprocessing.Dist2Depth"}
        ]
      }
    },
    {
      "module": "writer.Hdf5Writer"
    }
  ]
}
