# Args: <obj_file> <output_dir>
{
  "version": 1,
  "setup": {
    "blender_install_path": "/home_local/<env:USER>/blender/",
    "blender_version": "blender-2.81-linux-glibc217-x86_64",
    "pip": [
      "h5py",
      "imageio"
    ]
  },
  "global": {
    "all": {
      "output_dir": "<args:1>"
    }
  },
  "modules": [
    {
      "name": "main.Initializer",
      "config": {}
    },
    {
      "name": "loader.ObjectLoader",
      "config": {
        "path": "<args:0>"
      }
    },
    {
      "name": "lighting.LightLoader",
      "config": {
        "lights": [
          {
            "type": "POINT",
            "location": [5, -5, 5],
            "energy": 1000
          }
        ]
      }
    },
    {
      "name": "camera.CameraSampler",
      "config": {
        "cam_poses": [
          {
            "location": {
              "name":"sampler.Uniform3d",
              "max":[10, 10, 8],
              "min":[-10, -10, 12]
            },
            "rotation": {
              "format": "look_at",
              "value": {
                "name": "getter.POI"
              }
            }
          }
        ]
      }
    },
    {
      "name": "renderer.NormalRenderer",
      "config": {
        "output_key": "normals"
      }
    },
    {
      "name": "renderer.RgbRenderer",
      "config": {
        "output_key": "colors",
        "samples": 350
      }
    },
    {
      "name": "writer.Hdf5Writer",
      "config": {
      }
    }
  ]
}