name: BlenderProcHelper

on: [pull_request, workflow_dispatch]
  
jobs:
  Run-BlenderProcHelper:
    runs-on: [self-hosted]
    strategy:
      max-parallel: 1
    steps:
    - uses: actions/checkout@v2
    - name: Run BlenderProcHelper
      run: python3 /home/$USER/workspace/BlenderProcHelper/github_action.py
    - name: Archive logs
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: artifacts
